### PR TITLE
pkg: publish dist

### LINKED ISSUE #23: package not being published correctly
hello, if you install latest from npm, you'll see that the `dist` folder is not present, basically the compiled source code is missing.

the last version that can be used is 0.0.13

### PR DESCRIPTION
**Pull request by tomholford**
This resolves #23 by removing dist/ from .gitignore and checking it into source control for future publishing to npm by @samuraitruong.

Built with node 16.14.0

### CODE REVIEW

**Comment by tomholford** [comment]
@samuraitruong Please take a look at your convenience

**Comment by dmytrotkk** [comment]
bumping this one, since npm builds are still broken 

CC @samuraitruong

**Comment by samuraitruong** [comment]
@dmytrotkk  I don't think we need to commit the dist folder unless you install from github. can you install it from npm instead?

**Comment by samuraitruong** [comment]
please checkout latest version. I fixed the CI to enforcing the build command

**Pull request closed without merging**
